"use client";

import React, { useState, useEffect } from "react";
import { AppShell } from "@/components/layout/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Modal } from "@/components/ui/modal";
import { PriorityBadge } from "@/components/ui/status-badge";
import { EmptyState } from "@/components/ui/empty-state";
import { Skeleton } from "@/components/ui/skeleton";
import { formatDate } from "@/lib/utils";
import {
  CheckSquare,
  Plus,
  Clock,
  AlertCircle,
  Calendar,
  CheckCircle2,
} from "lucide-react";

export default function TasksPage() {
  const [tasks, setTasks] = useState<any[]>([]);
  const [counts, setCounts] = useState({ all: 0, overdue: 0, today: 0, upcoming: 0, completed: 0 });
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState("all");

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [formData, setFormData] = useState({
    title: "",
    description: "",
    priority: "MEDIUM",
    dueDate: "",
    assignee: "Sales Rep",
  });

  const fetchTasks = async () => {
    setLoading(true);
    try {
      const q = new URLSearchParams({ filter });
      const res = await fetch(`/api/tasks?${q.toString()}`);
      const data = await res.json();
      if (res.ok && data?.data) {
        setTasks(data.data.tasks || []);
        if (data.data.counts) setCounts(data.data.counts);
      }
    } catch {
      // ignore
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchTasks();
  }, [filter]);

  const toggleTaskStatus = async (task: any) => {
    const nextStatus = task.status === "COMPLETED" ? "TODO" : "COMPLETED";
    try {
      await fetch(`/api/tasks/${task._id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status: nextStatus }),
      });
      fetchTasks();
    } catch {
      // ignore
    }
  };

  const handleCreateTask = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    try {
      const res = await fetch("/api/tasks", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(formData),
      });

      if (res.ok) {
        setIsModalOpen(false);
        setFormData({
          title: "",
          description: "",
          priority: "MEDIUM",
          dueDate: "",
          assignee: "Sales Rep",
        });
        fetchTasks();
      }
    } catch {
      // ignore
    } finally {
      setIsSubmitting(false);
    }
  };

  const tabs = [
    { id: "all", label: "All Tasks", count: counts.all },
    { id: "overdue", label: "Overdue", count: counts.overdue },
    { id: "today", label: "Today", count: counts.today },
    { id: "upcoming", label: "Upcoming", count: counts.upcoming },
    { id: "completed", label: "Completed", count: counts.completed },
  ];

  return (
    <AppShell>
      <div className="space-y-6 animate-fade-in">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-b border-[#ECE7DE] pb-5">
          <div>
            <h1 className="text-2xl font-bold tracking-tight text-[#1C1B18]">
              Sales Follow-up Tasks
            </h1>
            <p className="text-xs text-[#5C5850] mt-1">
              Automated and manual outreach tasks generated by AI qualification and Twenty CRM
            </p>
          </div>

          <Button
            variant="primary"
            size="sm"
            onClick={() => setIsModalOpen(true)}
            className="text-xs"
          >
            <Plus className="w-3.5 h-3.5 mr-1" />
            Add Task
          </Button>
        </div>

        {/* Tab Filters */}
        <div className="flex items-center gap-1 border-b border-[#ECE7DE] overflow-x-auto no-scrollbar">
          {tabs.map((tab) => {
            const isActive = filter === tab.id;
            return (
              <button
                key={tab.id}
                onClick={() => setFilter(tab.id)}
                className={`flex items-center gap-2 px-3.5 py-2.5 text-xs font-semibold whitespace-nowrap border-b-2 transition-all cursor-pointer ${isActive
                  ? "border-[#8D5B28] text-[#8D5B28] bg-[#F6EDE3]/40"
                  : "border-transparent text-[#5C5850] hover:text-[#1C1B18]"
                  }`}
              >
                <span>{tab.label}</span>
                <span
                  className={`px-1.5 py-0.2 rounded-full text-[10px] ${isActive ? "bg-[#8D5B28] text-white" : "bg-[#F3EFE7] text-[#5C5850]"
                    }`}
                >
                  {tab.count}
                </span>
              </button>
            );
          })}
        </div>

        {/* Tasks List */}
        <div className="rounded-xl border border-[#ECE7DE] bg-white shadow-2xs overflow-hidden">
          {loading ? (
            <div className="p-6 space-y-3">
              {Array.from({ length: 4 }).map((_, i) => (
                <Skeleton key={i} className="h-16 w-full rounded" />
              ))}
            </div>
          ) : tasks.length === 0 ? (
            <EmptyState
              title="No tasks in this view"
              description="Everything is caught up. Create a task or switch your tab filter."
              actionLabel="Create Task"
              onAction={() => setIsModalOpen(true)}
            />
          ) : (
            <div className="divide-y divide-[#ECE7DE]">
              {tasks.map((task) => {
                const isDone = task.status === "COMPLETED";

                return (
                  <div
                    key={task._id}
                    className={`flex items-start justify-between p-4 transition-colors hover:bg-[#FAF8F5] text-xs ${isDone ? "opacity-60 bg-[#FAF8F5]/40" : ""
                      }`}
                  >
                    <div className="flex items-start gap-3.5">
                      <button
                        onClick={() => toggleTaskStatus(task)}
                        className={`mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center rounded border transition-colors cursor-pointer ${isDone
                          ? "border-[#246E47] bg-[#246E47] text-white"
                          : "border-[#D9D2C4] bg-white hover:border-[#8D5B28]"
                          }`}
                      >
                        {isDone && <CheckCircle2 className="w-3.5 h-3.5" />}
                      </button>

                      <div>
                        <div
                          className={`font-semibold text-[#1C1B18] ${isDone ? "line-through text-[#8C867B]" : ""
                            }`}
                        >
                          {task.title}
                        </div>
                        {task.description && (
                          <p className="mt-1 text-[11px] text-[#5C5850]">
                            {task.description}
                          </p>
                        )}
                        <div className="mt-2 flex flex-wrap items-center gap-3 text-[11px] text-[#8C867B]">
                          {task.companyName && <span>Account: {task.companyName}</span>}
                          {task.leadName && <span>Contact: {task.leadName}</span>}
                          <span>Assignee: {task.assignee}</span>
                        </div>
                      </div>
                    </div>

                    <div className="text-right shrink-0">
                      <PriorityBadge priority={task.priority} />
                      <div className="mt-1.5 flex items-center justify-end gap-1 text-[10px] text-[#8C867B]">
                        <Calendar className="w-3 h-3" />
                        <span>{formatDate(task.dueDate)}</span>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Create Task Modal */}
        <Modal
          isOpen={isModalOpen}
          onClose={() => setIsModalOpen(false)}
          title="Create Follow-up Task"
          description="Schedules a task for your team, visible in LeadFlow and synchronized to Twenty CRM."
        >
          <form onSubmit={handleCreateTask} className="space-y-4">
            <Input
              label="Task Title *"
              required
              placeholder="Call Marcus Sterling to review freight specs"
              value={formData.title}
              onChange={(e) => setFormData({ ...formData, title: e.target.value })}
            />

            <Textarea
              label="Description / Context"
              placeholder="Add action items or meeting notes..."
              rows={3}
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
            />

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <Select
                label="Priority"
                value={formData.priority}
                onChange={(e) => setFormData({ ...formData, priority: e.target.value })}
                options={[
                  { label: "High", value: "HIGH" },
                  { label: "Medium", value: "MEDIUM" },
                  { label: "Low", value: "LOW" },
                ]}
              />
              <Input
                label="Due Date"
                type="date"
                value={formData.dueDate}
                onChange={(e) => setFormData({ ...formData, dueDate: e.target.value })}
              />
            </div>

            <Input
              label="Assignee"
              placeholder="Sales Rep / Alex Vance"
              value={formData.assignee}
              onChange={(e) => setFormData({ ...formData, assignee: e.target.value })}
            />

            <div className="flex flex-col-reverse sm:flex-row sm:justify-end gap-2.5 pt-3 border-t border-[#ECE7DE]">
              <Button type="button" variant="outline" size="sm" onClick={() => setIsModalOpen(false)} className="w-full sm:w-auto">
                Cancel
              </Button>
              <Button type="submit" variant="primary" size="sm" isLoading={isSubmitting} className="w-full sm:w-auto">
                Save Task
              </Button>
            </div>
          </form>
        </Modal>
      </div>
    </AppShell>
  );
}
